### ISSUE TITLE
docs: not explained why MID is optional

### ISSUE THREAD

**Issue by JoernBerkefeld** [FiB3/ssjs-vsc#2]
> "sfmc-mid": "<< optional: only if MID is needed >>",

explain what "if needed" means and what to do if it's "not needed"

**Comment by FiB3** [comment]
If you are in the context of the Business Unit that was used your Installed Package, then you do not need to use MID when authenticating to SFMC.
So, in a single Business Unit Instance, you do not need to worry about this parameter at all.

Will make it clearer in the docs and setup.

**Comment by JoernBerkefeld** [comment]
to keep things easy maybe state that you need to define the MID of the BU you are working in at all times. even if _technically_ that's not always the case. One thing less for users to wrap their heads around

**Comment by FiB3** [comment]
I added a bit of an explanation to the new Walkthrough (new command: `SSJS: Show Setup Walkthrough`). Also added a little bit of an explanation on the Extension page.
Removed the `if needed` from the setup dialog that you have mentioned.

**Comment by FiB3** [comment]
Explained in multiple places including the new Config Panel that simplifies the config.
