### ISSUE TITLE
docs: explain Server & Asset provider settings

### ISSUE THREAD

**Issue by JoernBerkefeld** [FiB3/ssjs-vsc#3]
it's unclear to me what that is for and how to use it. I can only assume others might struggle with that as well

**Comment by FiB3** [comment]
This page describes both code providers:
https://fib3.github.io/ssjs-vsc/extension/extension/#deployment-options

Is this sufficient? The setup of the default Asset Provider is described in multiple places.

**Comment by FiB3** [comment]
This page describes both code providers:
https://fib3.github.io/ssjs-vsc/extension/extension/#deployment-options

Is this sufficient? The setup of the default Asset Provider is described in multiple places.

**Comment by JoernBerkefeld** [comment]
that link doesnt work :-( it gives me a 404. maybe a permission issue?

**Comment by FiB3** [comment]
Nah, wrong link (for some reason double "extension"). Correct one is: https://fib3.github.io/ssjs-vsc/extension/#deployment-options
