### ISSUE TITLE
docs: dev / prod tokens definition / use case?

### ISSUE THREAD

**Issue by JoernBerkefeld** [FiB3/ssjs-vsc#4]
whats that for? is that supposed to be templating / auto-replacement logic? if yes, could you provide a real-life example to make it easy to understand? 

you mention it on https://fib3.github.io/ssjs-vsc/settings/ and on https://fib3.github.io/ssjs-vsc/use/ but neither description is giving actual examples

**Comment by FiB3** [comment]
This one can be pretty useful in two cases:
- you need to set some values differently when developing and when in prod. The Prod is for future use (I want to add deploy feature, that would create/update script activities or assets etc.).
- Also, this can be useful when you want to share your code with somebody, but do not want to share some values - like credentials etc.

I will add a more thorough explanation to the page.

A simple example though:
```html
<script runat=server>
   var IS_PROD = {{IS_PROD}};
   var MC_SUBDOMAIN = "{{SUBDOMAIN}}";
   var CLIENT_ID = "{{CLIENT_ID}}";
   var CLIENT_SECRET = "{{CLIENT_SECRET}}";
   
</script>
```

```json
{ //...
   {
     "dev-tokens": {
      "IS_PROD": false,
      "MC_SUBDOMAIN": "mc-dummy-subdomain",
      "CLIENT_ID": "cl-id-12345",
      "CLIENT_ID": "cl-secret-98765"
    },
    "prod-tokens": {
    },
    /...
 }
```

**Comment by JoernBerkefeld** [comment]
ok, that is in fact what we call templating in mcdev. had a feeling but wasn't sure. 
I'm assuming you use Mustache? You might want to consider using 3 curly brackets because that ensures the text is used as-is. otherwise it might end up doing some unwanted extra conversions...

**Comment by FiB3** [comment]
Yup, it's templating & Mutache. The name "tokens" is a bit of a legacy thing.

Good idea, GTL probably will not be supported in the current implementation. But that way I will probably need to choose another templating package.

**Comment by FiB3** [comment]
I am adding this to `Usage` tab on the page.

**Comment by FiB3** [comment]
I am preparing a new version of the extension, that has an option to set the Mustache Tags.
![image](https://github.com/FiB3/ssjs-vsc/assets/26510307/cfff3429-d7eb-4e75-8734-87d85115d7e0)

**Comment by JoernBerkefeld** [comment]
good thinking :)

**Comment by FiB3** [comment]
Deployed yesterday in v0.2.0.

**Comment by FiB3** [comment]
There is way more documentation on this topic now:
https://fib3.vercel.app/ssjs-vsc/4_templating
Also, since v0.4.4 (will be pre-released today) you can set these in the Config Panel.
