### ISSUE TITLE
docs: how to set up code provider and what is it?

### ISSUE THREAD

**Issue by JoernBerkefeld** [FiB3/ssjs-vsc#6]
yup. dont know what that means

source: https://fib3.github.io/ssjs-vsc/use/

**Comment by FiB3** [comment]
Right! :D Another docs improvement.

Code Provider is the way SSJS Manager shares the code to SFMC behind the scene. Their differences are described [in the Extension tab](https://fib3.github.io/ssjs-vsc/extension/).

You can probably use the default "Asset Provider".

**Comment by FiB3** [comment]
I improved the docs so this is more clear, and added a few links so it's more clear.
