### ISSUE TITLE
docs: how to create your first .ssjs file 

### ISSUE THREAD

**Issue by JoernBerkefeld** [FiB3/ssjs-vsc#7]
on the server?
in vscode?
where?
name/key?

source: https://fib3.github.io/ssjs-vsc/use/

**Comment by FiB3** [comment]
In the VSCode :D
Will update the docs :)

**Comment by FiB3** [comment]
Updated in the page.

**Comment by JoernBerkefeld** [comment]
is that update published already? somehow cant see it I think

**Comment by FiB3** [comment]
It's only in the wording. 
<img width="729" alt="image" src="https://github.com/FiB3/ssjs-vsc/assets/26510307/941d1eaa-909e-4410-997a-f702a6e1bc47">
